name: emrecharge_apps

channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.10
  - cython
  - numpy
  - scipy
  - matplotlib
  - pandas
  - SimPEG
  - ipykernel
  - ipywidgets
  - ipympl
  - discretize
  - dill
  - pip
  - pip:
      - emrecharge
